input_select:
    previous_aqi_level:
      options:
        - 0_to_50
        - 51_to_100
        - 101_to_150
        - 151_to_200
        - 201_to_300
        - 300_plus

    aqi_level:
      options:
        - 0_to_50
        - 51_to_100
        - 101_to_150
        - 151_to_200
        - 201_to_300
        - 300_plus

sensor:
  - platform: template
    sensors:
      aqi_level_sensor:
        value_template: >-
          {% if states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 50 %}
            0_to_50
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 100 %}
            51_to_100
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 150 %}
            101_to_150
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 200 %}
            151_to_200
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 300 %}
            201_to_300
          {% else %}
            300_plus
          {% endif %}
      aqi_level_text:
        value_template: >-
          {% if states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 50 %}
            good
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 100 %}
            moderate
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 150 %}
            unhealthy for sensitive groups
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 200 %}
            unhealthy
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 300 %}
            very unhealthy
          {% else %}
            hazardous
          {% endif %}


automation:
  - id: update_aqi_every_hour
    alias: 'Update AQI Every Hour'
    trigger:
      platform: time_pattern
      minutes: '/60'
      seconds: 0
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.previous_aqi_level
          option: '{{ states.input_select.aqi_level.state }}'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.aqi_level
          option: '{{ states.sensor.aqi_level_sensor.state }}'
      - condition: and
        conditions:
          - condition: template
            value_template: '{{ states.input_select.aqi_level.state != states.input_select.previous_aqi_level.state }}'
          - condition: template
            value_template: '{{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 | int > 100 }}'
      - service: notify.telegram
        data_template:
          message: >-
            Air Quality in Taipei is {{ states.sensor.aqi_level_text.state }}
            (AQI {{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 }} pm2.5)
      - condition: template
        value_template: '{{ states.sensor.bedroom_aqi.state | int > 50 }}'
      - service: notify.telegram_admin
        data:
          message: >-
            Current pollution level is {{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 }} outside
            and {{ states.sensor.bedroom_aqi.state }} in the bedroom.
            Do you want to take action for the air purifier?
            data:
              inline_keyboard:
                - 'Turn on:/turnon, Turn off:/turnoff'

  - id: telegram_callback_air_purifier_turn_on
    alias: 'Telegram Callback Turn ON Air Purifier'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/turnon'
    action:
      - service: fan.set_speed
        entity_id: fan.mi_air_purifier_2
        data:
          speed: auto

  - id: telegram_callback_air_purifier_turn_off
    alias: 'Telegram Callback Turn OFF Air Purifier'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/turnoff'
    action:
      - service: fan.set_speed
        entity_id: fan.mi_air_purifier_2
        data:
          speed: idle
