input_select:
    previous_aqi_level:
      options:
        - 0_to_50
        - 51_to_100
        - 101_to_150
        - 151_to_200
        - 201_to_300
        - 300_plus

    aqi_level:
      options:
        - 0_to_50
        - 51_to_100
        - 101_to_150
        - 151_to_200
        - 201_to_300
        - 300_plus

sensor:
  - platform: template
    sensors:
      aqi_level_sensor:
        value_template: >-
          {% if states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 50 %}
            0_to_50
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 100 %}
            51_to_100
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 150 %}
            101_to_150
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 200 %}
            151_to_200
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 300 %}
            201_to_300
          {% else %}
            300_plus
          {% endif %}
      aqi_level_text:
        value_template: >-
          {% if states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 50 %}
            good
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 100 %}
            moderate
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 150 %}
            unhealthy for sensitive groups
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 200 %}
            unhealthy
          {% elif states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 <= 300 %}
            very unhealthy
          {% else %}
            hazardous
          {% endif %}


automation:
  - id: update_aqi_every_hour
    trigger:
      platform: time
      minutes: '/60'
      seconds: 0
    action:
      - service: input_select.set_option
        data_template:
          entity_id: input_select.previous_aqi_level
          option: '{{ states.input_select.aqi_level.state }}'
      - service: input_select.set_option
        data_template:
          entity_id: input_select.aqi_level
          option: '{{ states.sensor.aqi_level_sensor.state }}'
      - condition: template
        value_template: '{{ states.input_select.aqi_level.state != states.input_select.previous_aqi_level.state }}'
      - service: notify.telegram
        data_template:
          message: >-
            Just a little message to inform you of the current pollution in Taipei.
            With a AQI of {{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 }}, the current
            condition is {{ states.sensor.aqi_level_text.state }}!
            {% if states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 > 100 %}
            Please be careful when going out as the air pollution starts to be serious.
            {% endif %}
            You can visit http://aqicn.org/scale/ for more information about the air quality index scale :)
      - condition: template
        value_template: '{{ states.sensor.bedroom_aqi.state > 50 }}'
      - service: notify.telegram_admin
        data:
          message: >-
            Current pollution level is {{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 }} outside
            and {{ states.sensor.bedroom_aqi.state }} in the bedroom.
            Do you want to take action for the air purifier?
            data:
              inline_keyboard:
                - 'Turn on:/turnon, Turn off:/turnoff'

  - id: telegram_callback_air_purifier_turn_on
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/turnon'
    action:
      - service: fan.set_speed
        entity_id: fan.mi_air_purifier_2
        data:
          speed: auto

  - id: telegram_callback_air_purifier_turn_off
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/turnoff'
    action:
      - service: fan.set_speed
        entity_id: fan.mi_air_purifier_2
        data:
          speed: idle
