input_boolean:
  alarm_enabled:
    name: Enable alarm (doors only)
    icon: mdi:toggle-switch
  alarm_enabled_all:
    name: Enable alarm (all)
    icon: mdi:toggle-switch

group:
    alarm:
      name: Alarm
      entities:
        - input_boolean.alarm_enabled
        - input_boolean.alarm_enabled_all
        - script.control_alarm

automation:
  - id: start_alarm_when_door_opens
    alias: 'Start alarm When Door Opens'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00012153cf # front door
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.alarm_enabled
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret mac_gateway_ludo
          ringtone_id: 2
          ringtone_vol: 73
      - service: light.turn_on
        data:
          entity_id: group.lights_living_room
          effect: 'Alarm'
      - service: notify.telegram_admin
        data:
          message: 'Alarm has been triggered!'

  - id: start_alarm_if presence_motion_or_door_is_detected
    alias: 'Start Alarm If Presence Motion Or Door Is Detected'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00012153cf # front door
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00018311c8 # bedroom door
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001225132 # bedroom motion sensor
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d00020dc8b6 # kitchen motion sensor
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.alarm_enabled_all
        state: 'on'
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret mac_gateway_ludo
          ringtone_id: 2
          ringtone_vol: 73
      - service: light.turn_on
        data:
          entity_id: group.lights_living_room
          effect: 'Alarm'
      - service: notify.telegram_admin
        data:
          message: 'Alarm has been triggered!'

script:
  stop_alarm:
    sequence:
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret mac_gateway_ludo
      - service: light.turn_on
        data:
          entity_id: group.lights_living_room
          rgb_color: [255,160, 50]
      - service: light.turn_off
        data:
          entity_id: group.lights_living_room

  control_alarm:
    sequence:

homeassistant:
  customize:
    script.control_alarm:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 2
        row_height: 75px
        columen_width: 85px
        gap: 10px
        color: '#353B65'
        entities:
          - entity: script.stop_alarm
            icon: mdi:stop
            column_span: 2
