input_select:
    trashbags:
      name: Trash bags
      icon: mdi:delete
      options:
        - None
        - Small
        - Big
        - Both small and big

input_text:
  other1:
    name: Other 1
  other2:
    name: Other 2
  other3:
    name: Other 3

input_boolean:
# Kitchen
  dishliquid:
    name: Dish liquid
    icon: mdi:water
  sponge:
    name: Sponge
    icon: mdi:water
  papertowel:
    name: Paper towel
    icon: mdi:water

# bathroom
  bodysoap:
    name: Body soap
    icon: mdi:shower-head
  shampoo:
    name: Shampoo
    icon: mdi:shower-head
  handsoap:
    name: Hand soap
    icon: mdi:shower-head
  toothbrush:
    name: Toothbrush
    icon: mdi:shower-head
  toothpaste:
    name: Toothpaste
    icon: mdi:shower-head
  cottonswab:
    name: Cotton swab
    icon: mdi:shower-head
  toiletpaper:
    name: Toilet paper
    icon: mdi:toilet

# cleaning
  bakingsoda:
    name: Baking soda
    icon: mdi:water
  laundrydetergent:
    name: Laundry detergent
    icon: mdi:water
  floorcleaner:
    name: Floor cleaner
    icon: mdi:water
  glasscleaner:
    name: Glass cleaner
    icon: mdi:water

# food & drink
  orangejuice:
    name: Orange juice
    icon: mdi:food-variant
  soymilk:
    name: Soy milk
    icon: mdi:food-variant
  milk:
    name: Milk
    icon: mdi:food-variant
  eggs:
    name: Eggs
    icon: mdi:food-variant
  cereal:
    name: Cereal
    icon: mdi:food-variant
  nutella:
    name: Nutella
    icon: mdi:food-variant
  bread:
    name: Bread
    icon: mdi:food-variant
  salt:
    name: Salt
    icon: mdi:food-variant
  pepper:
    name: Pepper
    icon: mdi:food-variant


group:
  shopping_kitchen:
    name: Kitchen
    entities:
      - input_boolean.dishliquid
      - input_boolean.sponge
      - input_boolean.papertowel

  shopping_bathroom:
    name: Bathroom
    entities:
      - input_boolean.bodysoap
      - input_boolean.shampoo
      - input_boolean.handsoap
      - input_boolean.toothbrush
      - input_boolean.toothpaste
      - input_boolean.cottonswab
      - input_boolean.toiletpaper

  shopping_cleaning:
    name: Cleaning
    entities:
      - input_boolean.bakingsoda
      - input_boolean.laundrydetergent
      - input_boolean.floorcleaner
      - input_boolean.glasscleaner

  shopping_food_drink:
    name: Food & drink
    entities:
      - input_boolean.orangejuice
      - input_boolean.soymilk
      - input_boolean.milk
      - input_boolean.eggs
      - input_boolean.cereal
      - input_boolean.nutella
      - input_boolean.bread
      - input_boolean.salt
      - input_boolean.pepper

  shopping_others:
    name: Others
    entities:
      - input_select.trashbags
      - input_text.other1
      - input_text.other2
      - input_text.other3


automation:
  - id: shopping
    trigger:
      - platform: zone
        entity_id: device_tracker.taras_phone
        zone: zone.carrefour
        event: enter
      - platform: zone
        entity_id: device_tracker.taras_phone
        zone: zone.px_mart
        event: enter
      - platform: zone
        entity_id: device_tracker.ludos_phone
        zone: zone.carrefour
        event: enter
      - platform: zone
        entity_id: device_tracker.ludos_phone
        zone: zone.px_mart
        event: enter
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.shopping_kitchen
          state: 'on'
        - condition: state
          entity_id: group.shopping_bathroom
          state: 'on'
        - condition: state
          entity_id: group.shopping_cleaning
          state: 'on'
        - condition: state
          entity_id: group.shopping_food_drink
          state: 'on'
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ states.input_select.trashbags.state != "None" }}'
            - condition: template
              value_template: '{{ states.input_text.other1.state !=  ""  }}'
            - condition: template
              value_template: '{{ states.input_text.other2.state !=  ""  }}'
            - condition: template
              value_template: '{{ states.input_text.other3.state !=  ""  }}'
    action:
      - service: notify.telegram_admin
        data_template:
          message: >-
            There are a few 這個那個s to buy :)
            {% if is_state("input_boolean.dishliquid", "on") %}
              - {{ states.input_boolean.dishliquid.name }}
            {% endif %}
            {% if is_state("input_boolean.sponge", "on") %}
              - {{ states.input_boolean.sponge.name }}
            {% endif %}
            {% if is_state("input_boolean.papertowel", "on") %}
              - {{ states.input_boolean.papertowel.name }}
            {% endif %}
            {% if is_state("input_boolean.bodysoap", "on") %}
              - {{ states.input_boolean.bodysoap.name }}
            {% endif %}
            {% if is_state("input_boolean.shampoo", "on") %}
              - {{ states.input_boolean.shampoo.name }}
            {% endif %}
            {% if is_state("input_boolean.handsoap", "on") %}
              - {{ states.input_boolean.handsoap.name }}
            {% endif %}
            {% if is_state("input_boolean.toothbrush", "on") %}
              - {{ states.input_boolean.toothbrush.name }}
            {% endif %}
            {% if is_state("input_boolean.toothpaste", "on") %}
              - {{ states.input_boolean.toothpaste.name }}
            {% endif %}
            {% if is_state("input_boolean.cottonswab", "on") %}
              - {{ states.input_boolean.cottonswab.name }}
            {% endif %}
            {% if is_state("input_boolean.toiletpaper", "on") %}
              - {{ states.input_boolean.toiletpaper.name }}
            {% endif %}
            {% if is_state("input_boolean.bakingsoda", "on") %}
              - {{ states.input_boolean.bakingsoda.name }}
            {% endif %}
            {% if is_state("input_boolean.laundrydetergent", "on") %}
              - {{ states.input_boolean.laundrydetergent.name }}
            {% endif %}
            {% if is_state("input_boolean.floorcleaner", "on") %}
              - {{ states.input_boolean.floorcleaner.name }}
            {% endif %}
            {% if is_state("input_boolean.glasscleaner", "on") %}
              - {{ states.input_boolean.glasscleaner.name }}
            {% endif %}
            {% if is_state("input_boolean.orangejuice", "on") %}
              - {{ states.input_boolean.orangejuice.name }}
            {% endif %}
            {% if is_state("input_boolean.soymilk", "on") %}
              - {{ states.input_boolean.soymilk.name }}
            {% endif %}
            {% if is_state("input_boolean.milk", "on") %}
              - {{ states.input_boolean.milk.name }}
            {% endif %}
            {% if is_state("input_boolean.eggs", "on") %}
              - {{ states.input_boolean.eggs.name }}
            {% endif %}
            {% if is_state("input_boolean.cereal", "on") %}
              - {{ states.input_boolean.cereal.name }}
            {% endif %}
            {% if is_state("input_boolean.nutella", "on") %}
              - {{ states.input_boolean.nutella.name }}
            {% endif %}
            {% if is_state("input_boolean.bread", "on") %}
              - {{ states.input_boolean.bread.name }}
            {% endif %}
            {% if is_state("input_boolean.salt", "on") %}
              - {{ states.input_boolean.salt.name }}
            {% endif %}
            {% if is_state("input_boolean.pepper", "on") %}
              - {{ states.input_boolean.pepper.name }}
            {% endif %}
            {% if not is_state("input_select.trashbags", "None") %}
              - Trash bag {{ states.input_select.trashbags.state }}
            {% endif %}
            {% if not is_state("input_text.other1", "")  %}
              - {{ states.input_text.other1.state }}
            {% endif %}
            {% if not is_state("input_text.other2", "")  %}
              - {{ states.input_text.other2.state }}
            {% endif %}
            {% if not is_state("input_text.other3", "")  %}
              - {{ states.input_text.other3.state }}
            {% endif %}
