homeassistant:
  customize:
    script.vacuum_remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 75px
        column_width: 85px
        gap: 10px
        color: '#353B65'
        entities:
#          - entity: script.vacuum_locate
#            icon: mdi:magnify
#            column_span: 2
#          - entity: script.vacuum_return_to_base
#            icon: mdi:home
#            column_span: 2
          - entity: script.vacuum_remote_control_start
            icon: mdi:play
            column_span: 2
          - entity: script.vacuum_remote_control_stop
            icon: mdi:stop
            column_span: 2
          - entity: script.vacuum_remote_control_turn_left_15
            icon: mdi:chevron-left
            column_span: 1
          - entity: script.vacuum_remote_control_turn_right_15
            icon: mdi:chevron-right
            column_span: 1
          - entity: script.vacuum_remote_control_move_foward_fast
            icon: mdi:chevron-double-up
            column_span: 2
          - entity: script.vacuum_remote_control_turn_left_45
            icon: mdi:rotate-left
            column_span: 1
          - entity: script.vacuum_remote_control_turn_right_45
            icon: mdi:rotate-right
            column_span: 1
          - entity: script.vacuum_remote_control_move_foward_slow
            icon: mdi:chevron-up
            column_span: 2


group:
  vacuum_control_panel:
    name: Vacuum Control Panel
    entities:
      - script.vacuum_remote_control
script:
  vacuum_remote_control:
    sequence:
