# Control Panel
homeassistant:
  customize:
    script.vacuum_remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 75px
        column_width: 85px
        gap: 10px
        color: '#353B65'
        entities:
#          - entity: script.vacuum_locate
#            icon: mdi:magnify
#            column_span: 2
#          - entity: script.vacuum_return_to_base
#            icon: mdi:home
#            column_span: 2
          - entity: script.vacuum_remote_control_start
            icon: mdi:play
            column_span: 2
          - entity: script.vacuum_remote_control_stop
            icon: mdi:stop
            column_span: 2
          - entity: script.vacuum_remote_control_turn_left_15
            icon: mdi:chevron-left
            column_span: 1
          - entity: script.vacuum_remote_control_turn_right_15
            icon: mdi:chevron-right
            column_span: 1
          - entity: script.vacuum_remote_control_move_foward_fast
            icon: mdi:chevron-double-up
            column_span: 2
          - entity: script.vacuum_remote_control_turn_left_45
            icon: mdi:rotate-left
            column_span: 1
          - entity: script.vacuum_remote_control_turn_right_45
            icon: mdi:rotate-right
            column_span: 1
          - entity: script.vacuum_remote_control_move_foward_slow
            icon: mdi:chevron-up
            column_span: 2

# Automatic Control
input_boolean:
  vacuum_schedule_weekdays:
    name: Enabled
    icon: mdi:toggle-switch
  vacuum_schedule_weekend:
    name: Enabled
    icon: mdi:toggle-switch

input_number:
  vacuum_schedule_weekdays_hour:
    name: Hour
    icon: mdi:clock-outline
    min: 0
    max: 23
    step: 1
  vacuum_schedule_weekdays_minute:
    name: Minute
    icon: mdi:clock-outline
    min: 0
    max: 45
    step: 15
  vacuum_schedule_weekend_hour:
    name: Hour
    icon: mdi:clock-outline
    min: 0
    max: 23
    step: 1
  vacuum_schedule_weekend_minute:
    name: Minute
    icon: mdi:clock-outline
    min: 0
    max: 45
    step: 15

script:
  vacuum_remote_control:
    sequence:

group:
  vacuum_control_panel:
    name: Vacuum Control Panel
    entities:
      - script.vacuum_remote_control
  vacuum_schedule_weekdays:
    name: Georgie's Schedule (Weekdays)
    entities:
      - sensor.vacuum_schedule_weekdays_template
      - input_boolean.vacuum_schedule_weekdays
      - input_number.vacuum_schedule_weekdays_hour
      - input_number.vacuum_schedule_weekdays_minute
  vacuum_schedule_weekend:
    name: Georgie's Schedule (Weekend)
    entities:
      - sensor.vacuum_schedule_weekend_template
      - input_boolean.vacuum_schedule_weekend
      - input_number.vacuum_schedule_weekend_hour
      - input_number.vacuum_schedule_weekend_minute

sensor:
  - platform: template
    sensors:
      vacuum_schedule_weekdays_template:
        friendly_name: 'Time'
        icon_template: "{{ 'mdi:timer' if is_state('input_boolean.vacuum_schedule_weekdays', 'on') else 'mdi:close-circle' }}"
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_schedule_weekdays_hour") | int, states("input_number.vacuum_schedule_weekdays_minute") | int) }}'
      vacuum_schedule_weekend_template:
        friendly_name: 'Time'
        icon_template: "{{ 'mdi:timer' if is_state('input_boolean.vacuum_schedule_weekend', 'on') else 'mdi:close-circle' }}"
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_schedule_weekend_hour") | int, states("input_number.vacuum_schedule_weekend_minute") | int) }}'


automation:
  - alias: vacuum_schedule
    trigger:
      - platform: time
        minutes: '/15'
        seconds: 00
    condition:
      condition: or
      conditions:
        - condition: and
          conditions:
          - condition: template
            value_template: '{{ now().time().strftime("%H:%M") == states.sensor.vacuum_schedule_weekdays_template.state }}'
          - condition: state
            entity_id: input_boolean.vacuum_schedule_weekdays
            state: 'on'
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
        - condition: and
          conditions:
          - condition: template
            value_template: '{{ now().time().strftime("%H:%M") == states.sensor.vacuum_schedule_weekend_template.state }}'
          - condition: state
            entity_id: input_boolean.vacuum_schedule_weekend
            state: 'on'
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'off'
    action:
      - service: script.vacuum_start_clean
