###############
# LIVING ROOM #
###############

- alias: Double click toggle sofa lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.sofa_lights

- alias: Single click toggle TV lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.tv_lights


###########
# KITCHEN #
###########

- alias: Long press toggle kitchen lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: long_click_press
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_lights

- alias: Turn on kitchen on motion at night time
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00020dc8b6
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        before_offset: "-00:30:00"
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_lights

- alias: Turn off kitchen after two minutes with no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00020dc8b6
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        before_offset: "-00:30:00"
  action:
    service: light.turn_off
    data:
      entity_id: light.kitchen_lights



###########
# BEDROOM #
###########

- alias: Shake cube toggle lights
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: shake_air
  action:
    service: light.toggle
    entity_id: light.bed_lights

- alias: Tap twice with cube turn on light (white, 100%)
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: tap_twice
  action:
    service: light.turn_on
    entity_id: light.bed_lights
    data:
      brightness: 255
      rgb_color: [255,255,255]

- alias: flip180 cube turn on light (orange, 30%)
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: flip180
  action:
    service: light.turn_on
    entity_id: light.bed_lights
    data:
      brightness: 76
      rgb_color: [255,165,0]

- alias: flip90 cube toggle desk light
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: flip90
  action:
    service: light.toggle
    entity_id: light.ludovics_desk

#- alias: Single click toggle bedroom lights
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d000121d17f
#      click_type: single
#  action:
#    service: light.toggle
#    data:
#      entity_id: light.bed_lights
#
#- alias: Double click toggle shower room lights
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d000121d17f
#      click_type: double
#  action:
#    service: light.toggle
#    data:
#      entity_id: light.shower_room

- alias: Motion detected turn on shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.shower_room

- alias: No motion for 5 minutes turn off shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.shower_room


##############
# FRONT DOOR #
##############

- alias: Turn on gateway light + Notify when door opened
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'off'
    to: 'on'
  action:
    - service: notify.telegram
      data:
        message: 'He did not hold the door'
    - service: notify.telegram_admin
      data:
        message: "The door has been opened"
        data:
          photo:
            - file: !secret file_path_camera
              caption: 'The door has been opened'
    - condition: and # if night and light not on
      conditions:
        - condition: state
          entity_id: light.sofa_lights
          state: 'off'
        - condition: state
          entity_id: light.tv_lights
          state: 'off'
        - condition: or
          conditions:
            - condition: sun
              after: sunset
              after_offset: "-01:00:00"
            - condition: sun
              before: sunrise
              before_offset: "-00:30:00"
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce0083878f
        brightness: 76
        rgb_color: [227,173,193]

- alias: Notify if door opened too long
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
    service: notify.telegram
    data:
      message: 'WARNING: The front door has been opened for 10 minutes'

- alias: Turn off gateway one minute after door closed
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'on'
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    data:
      entity_id: light.gateway_light_34ce0083878f

############
# TELEGRAM #
############

- alias: Send daily report every day at 8am
  trigger:
    platform: time
    at: '08:00:00'
  action:
    service: notify.telegram
    data_template:
      message: |
        早安！
        Today is {{ now().strftime("%B %d, %Y") }}.
        Currently it is {{ states.sensor.dark_sky_summary.state.lower() }}, {{ states.sensor.dark_sky_temperature.state  }}°C with {{ states.sensor.dark_sky_humidity.state | int }}% humidity and AQI is {{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 }} pm2.5 Taipei.
        The weather will be {{ states.sensor.dark_sky_hourly_summary.state.lower() }}
        You can expect temperatures between {{ states.sensor.dark_sky_daily_low_temperature.state }} and {{ states.sensor.dark_sky_daily_high_temperature.state }} degrees.
        Have a nice day :)
