###############
# LIVING ROOM #
###############

- id: Double_click_toggle_sofa_lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.sofa_lights

- id: Single_click_toggle_TV_lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.tv_lights


###########
# KITCHEN #
###########

- id: Long_press_toggle_kitchen_lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: long_click_press
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_lights

- id: Turn_on_kitchen_on_motion_at_night_time
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00020dc8b6
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        before_offset: "-00:30:00"
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_lights

- id: Turn_off_kitchen_after_two_minutes_with_no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00020dc8b6
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        before_offset: "-00:30:00"
  action:
    service: light.turn_off
    data:
      entity_id: light.kitchen_lights



###########
# BEDROOM #
###########

- id: Shake_cube_toggle_lights
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: shake_air
  action:
    service: light.toggle
    entity_id: light.bed_lights

- id: Tap_twice_with_cube_turn_on_light_(white 100percent)
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: tap_twice
  action:
    service: light.turn_on
    entity_id: light.bed_lights
    data:
      brightness: 255
      rgb_color: [255,255,255]

- id: flip180_cube_turn_on_light_(orange_30percent)
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: flip180
  action:
    service: light.turn_on
    entity_id: light.bed_lights
    data:
      brightness: 76
      rgb_color: [255,165,0]

- id: flip90_cube_toggle_desk_light
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: flip90
  action:
    service: light.toggle
    entity_id: light.ludovics_desk

#- id: Single_click_toggle_bedroom_lights
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d000121d17f
#      click_type: single
#  action:
#    service: light.toggle
#    data:
#      entity_id: light.bed_lights
#
#- id: Double_click_toggle_shower_room_lights
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d000121d17f
#      click_type: double
#  action:
#    service: light.toggle
#    data:
#      entity_id: light.shower_room

- id: Motion_detected_turn_on_shower_room_light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.shower_room

- id: No_motion_for_5_minutes_turn_off_shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.shower_room


##############
# FRONT DOOR #
##############

- id: Turn_on_gateway_light_+_Notify_when_door opened
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'off'
    to: 'on'
  action:
    - service: notify.telegram
      data:
        message: 'He did not hold the door'
    - service: notify.telegram_admin
      data:
        message: "The door has been opened"
        data:
          photo:
            - file: !secret file_path_camera
              caption: 'The door has been opened'
    - condition: and # if night and light not on
      conditions:
        - condition: state
          entity_id: light.sofa_lights
          state: 'off'
        - condition: state
          entity_id: light.tv_lights
          state: 'off'
        - condition: or
          conditions:
            - condition: sun
              after: sunset
              after_offset: "-01:00:00"
            - condition: sun
              before: sunrise
              before_offset: "-00:30:00"
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce0083878f
        brightness: 76
        rgb_color: [227,173,193]

- id: Notify_if_door_opened_too_long
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
    service: notify.telegram
    data:
      message: 'WARNING: The front door has been opened for 10 minutes'

- id: Turn_off_gateway_one_minute_after_door_closed
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'on'
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    data:
      entity_id: light.gateway_light_34ce0083878f


############
# TELEGRAM #
############

- id: Send_daily_report_every_day_at_8am
  trigger:
    platform: time
    at: '08:00:00'
  action:
    service: notify.telegram
    data_template:
      message: |
        早安！
        Today is {{ now().strftime("%B %d, %Y") }}.
        Currently it is {{ states.sensor.dark_sky_summary.state.lower() }}, {{ states.sensor.dark_sky_temperature.state  }}°C with {{ states.sensor.dark_sky_humidity.state | int }}% humidity and AQI is {{ states.sensor.waqi_zhongshan_taiwan.attributes.pm_2_5 }} pm2.5 Taipei.
        The weather will be {{ states.sensor.dark_sky_hourly_summary.state.lower() }}
        You can expect temperatures between {{ states.sensor.dark_sky_daily_low_temperature.state }} and {{ states.sensor.dark_sky_daily_high_temperature.state }} degrees.
        Have a nice day :)

- id: Send_logs
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /logs
  condition: []
  action:
    service: telegram_bot.send_document
    data:
      target:
        - !secret chat_id_telegram_admin
      file: !secret doc_log
      disable_notification: true
