###############
# LIVING ROOM #
###############

- alias: Double click toggle sofa lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.sofa_lights

- alias: Single click toggle TV lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.tv_lights


###########
# KITCHEN #
###########

- alias: Long press toggle kitchen lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001245482
      click_type: long_click_press
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_lights


################
# TL'S BEDROOM #
################

- alias: Shake cube toggle lights
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: shake_air
  action:
    service: light.toggle
    entity_id: light.bedroom_lights

- alias: Tap twice with cube turn on light (white, 100%)
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: tap_twice
  action:
    service: light.turn_on
    entity_id: light.bedroom_lights
    data:
      brightness: 255
      rgb_color: [255,255,255]

- alias: flip180 cube turn on light (orange, 30%)
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: flip180
  action:
    service: light.turn_on
    entity_id: light.bedroom_lights
    data:
      brightness: 76
      rgb_color: [255,165,0]

- alias: flip90 cube toggle desk light
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010f0603
      action_type: flip90
  action:
    service: light.toggle
    entity_id: light.ludovics_desk

- alias: Single click toggle bedroom lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000121d17f
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.bedroom_lights

- alias: Double click toggle shower room lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000121d17f
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.showeroom

- alias: Motion detected turn on bedroom lights
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001225132
    from: 'off'
    to: 'on'
  condition:
    condition: time
    after: '17:00:00'
    before: '06:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lights

- alias: No motion for 30 minutes turn off bedroom lights
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001225132
    from: 'on'
    to: 'off'
    for:
      minutes: 30
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_lights

- alias: Motion detected turn on shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.showeroom

- alias: No motion for 5 minutes turn off shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.showeroom


############
# BATHROOM #
############

- alias: Single click toggle bathroom lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000122ce3b
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.bathroom

- alias: Turn off light after 20 minutes
  trigger:
    platform: state
    entity_id: light.bathroom
    from: 'off'
    to: 'on'
    for:
      minutes: 20
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom

- alias: Motion detected turn on bathroom light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001225007
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom

- alias: No motion for 5 minutes turn off bathroom light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001225007
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom


#################
# JUSTIN'S ROOM #
#################

- alias: Single click toggle Justin's light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001562c66
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: group.justins_bedroom

###############
# SEAN'S ROOM #
###############


##############
# FRONT DOOR #
##############
- alias: Notify when door opened
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'off'
    to: 'on'
  action:
    service: notify.Telegram
    data:
      message: 'He did not hold the door'

- alias: Notify if door opened too long
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00012153cf
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
    service: notify.Telegram
    data:
      message: 'WARNING: The front door has been opened for 10 minutes'
