homeassistant:
  name: TechVille
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  packages: !include_dir_named config/packages/
  whitelist_external_dirs: !secret whitelisted_ext_dirs

# Enables the frontend
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5
#  cors_allowed_origins:
#    - https://reformedreality.com

tts:
  platform: google

# Checks for available updates
updater:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - group.all_automations

# Enables a map showing the location of tracked devices
map:

# Track the sun
#sun:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include config/floorplan.yaml


# Cloud
cloud:
  google_actions:
    filter:
      exclude_entities:
        - light.sink_right
        - light.sink_left
        - light.tv_up
        - light.tv_back
        - light.living_room_in
        - light.living_room_out
        - light.bed_l
        - light.bed_t
        - light.bed_under
      exclude_domains:
        - input_boolean
        - input_text
        - input_select
        - group
        - script
        - device_tracker
        - sensor
      include_entities:
        - script.toggle_ludovics_fan
        - script.turn_on_ludovics_ac
        - script.turn_off_ludovics_ac
    entity_config:
      light.ludovics_desk:
        name: Desk light
        aliases:
          - Desk
      light.gateway_light_34ce0083878f:
        name: Gateway light
        aliases:
          - Gateway
      light.shower_room:
        name: Shower room light
        aliases:
          - Shower room
      fan.mi_air_purifier_2:
        name: Air purifier
      script.toggle_ludovics_fan:
        name: Toggle fan
      script.turn_on_ludovics_ac:
        name: AC on
      script.turn_off_ludovics_ac:
        name: AC off

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: localhost
  username: !secret mosquitto_username
  password: !secret mosquitto_password
  port: 8883

sensor:
# Weather
  - platform: darksky
    api_key: !secret darksky_api
    units: auto
    monitored_conditions:
      - summary
      - hourly_summary
      - temperature
      - dew_point
      - humidity
      - temperature_max
      - temperature_min
      - precip_type
      - precip_probability
# Template
  - platform: template
    sensors:
      bedroom_temperature:
        friendly_name: "Room temperature"
        unit_of_measurement: "°C"
        value_template: "{{ states.fan.mi_air_purifier_2.attributes.temperature}}"
      bedroom_humidity:
        friendly_name: "Room Humidity"
        unit_of_measurement: "%"
        value_template: "{{ states.fan.mi_air_purifier_2.attributes.humidity}}"
      bedroom_aqi:
        friendly_name: "Room pollution"
        unit_of_measurement: "pm2.5"
        value_template: "{{ states.fan.mi_air_purifier_2.attributes.aqi}}"

# Air quality
  - platform: waqi
    token: !secret token_waqi
    locations:
      - Zhongshan, Taiwan

# Yeelight
light:
  - platform: yeelight
    devices:
      192.168.31.81:
        name: TV up
      192.168.31.184:
        name: TV back
      192.168.31.99:
        name: Sink Right
      192.168.31.8:
        name: Sink Left
      192.168.31.18:
        name: Bed L
      192.168.31.171:
        name: Bed T
      192.168.31.17:
        name: Bed under
      192.168.31.222:
        name: Ludovic's desk
      192.168.31.117:
        name: Shower room
      192.168.31.11:
        name: Living room in
      192.168.31.245:
        name: Living room out

  - platform: group
    name: Bedroom lights
    entities:
      - light.bed_t
      - light.bed_l
      - light.bed_under
      - light.ludovics_desk
      - light.shower_room
  - platform: group
    name: Bed lights
    entities:
      - light.bed_t
      - light.bed_l
      - light.bed_under
  - platform: group
    name: Living room lights
    entities:
      - light.living_room_in
      - light.living_room_out
      - light.tv_up
      - light.tv_back
  - platform: group
    name: Sofa lights
    entities:
      - light.living_room_in
      - light.living_room_out
  - platform: group
    name: TV lights
    entities:
      - light.tv_up
      - light.tv_back
  - platform: group
    name: Kitchen lights
    entities:
      - light.sink_right
      - light.sink_left

# Air purifier 2
fan:
  - platform: xiaomi_miio
    name: Mi Air Purifier 2
    host: !secret host_air_purifier
    token: !secret token_air_purifier

# Gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret mac_gateway_ludo
      key: !secret key_gateway_ludo
      host: !secret host_gateway_ludo

# Switch
switch:
  - platform: xiaomi_miio
    name: Smart Plug
    host: !secret host_smart_plug
    token: !secret token_smart_plug

# IR Remote
remote: !include config/xiaomi_ir_remote.yaml

# Xiaomi Vacuum
vacuum:
  - platform: xiaomi_miio
    host: !secret host_vacuum
    token: !secret token_vacuum

# Google cast
cast:
  media_player:
  - name: Chromcast
    platform: cast
    host: !secret host_chromecast
  - name: Teddy
    platform: cast
    host: !secret host_teddy_google_home
  - name: Bobby
    platform: cast
    host: !secret host_bobby_google_home

# Tracker
device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 50

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 20
  - name: Carrefour
    latitude: !secret latitude_carrefour
    longitude: !secret longitude_carrefour
    radius: 50
  - name: PX Mart
    latitude: !secret latitude_px_mart
    longitude: !secret longitude_px_mart
    radius: 50
  - name: Wellcome
    latitude: !secret latitude_wellcome
    longitude: !secret longitude_wellcome
    radius: 50
  - name: Office Ludovic
    latitude: !secret latitude_office_ludo
    longitude: !secret longitude_office_ludo
    radius: 20

# Camera
camera:
  # Weather satellite
  - platform: generic
    name: Taiwan Weather Satellite
    still_image_url: !secret url_weather_satellite_taipei
  # Security camera
  - platform: mjpeg
    name: Living Room Live
    mjpeg_url: !secret mjpeg_url_camera

binary_sensor:
# MQTT binary sensor
  - name: camera
    icon: cctv
    platform: mqtt
    state_topic: "living_room/camera"
    sensor_class: motion
# Workday
  - platform: workday
    country: !secret wd_country_code
    excludes: holiday

# IFTTT
ifttt:
  key: !secret ifttt_key

# Telegram
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret chat_id_telegram
  - name: telegram_admin
    platform: telegram
    chat_id: !secret chat_id_telegram_admin
  - name: Push
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

telegram_bot:
  platform: polling
  api_key: !secret api_key_telegram
  allowed_chat_ids:
    - !secret chat_id_telegram
    - !secret chat_id_telegram_admin
    - !secret chat_id_ludo
