homeassistant:
  name: TechVille
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml
  packages: !include_dir_named config/packages/

# Enables the frontend
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  cors_allowed_origins:
    - https://reformedreality.com

# Checks for available updates
updater:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - group.all_automations

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include config/floorplan.yaml


# Cloud
cloud:
  alexa:
    filter:
      exclude_entities:
        - sensor.dark_sky_summary
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature
        - sensor.dark_sky_precip
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
    entity_config:
      group.tv:
        name: TV lights
        description: Control ledstrips for the TV

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

hue:
  bridges:
    - host: 192.168.31.154
      allow_unreachable: true
      allow_hue_groups: false

sensor:
# Weather
  - platform: darksky
    api_key: !secret darksky_api
    units: auto
    monitored_conditions:
      - summary
      - temperature
      - temperature_max
      - temperature_min
      - precip_type
      - precip_probability

# Air quality
  - platform: waqi
    token: !secret token_waqi
    locations:
      - Zhongshan, Taiwan

# Yeelight
light:
  - platform: yeelight
    devices:
      192.168.31.81:
        name: TV up
      192.168.31.184:
        name: TV back
      192.168.31.99:
        name: Sink Right
      192.168.31.8:
        name: Sink Left
      192.168.31.18:
        name: Bed L
      192.168.31.171:
        name: Bed T
      192.168.31.17:
        name: Bed under
      192.168.31.222:
        name: Ludovic's desk
      192.168.31.117:
        name: Showeroom
      192.168.31.76:
        name: Bathroom
      192.168.31.11:
        name: Living room in
      192.168.31.245:
        name: Living room out

  - platform: group
    name: Bedroom lights
    entities:
      - light.bed_t
      - light.bed_l
      - light.bed_under
  - platform: group
    name: Living room lights
    entities:
      - light.living_room_in
      - light.living_room_out
      - light.tv_up
      - light.tv_down
  - platform: group
    name: Sofa lights
    entities:
      - light.living_room_in
      - light.living_room_out
  - platform: group
    name: TV lights
    entities:
      - light.tv_up
      - light.tv_back
  - platform: group
    name: Kitchen lights
    entities:
      - light.sink_right
      - light.sink_left

# Air purifier 2
fan:
  - platform: xiaomi_miio
    name: Mi Air Purifier 2
    host: !secret host_air_purifier
    token: !secret token_air_purifier

# Gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret mac_gateway_sean
      key: !secret key_gateway_sean
      host: !secret host_gateway_sean
    - mac: !secret mac_gateway_ludo
      key: !secret key_gateway_ludo
      host: !secret host_gateway_ludo

# IR Remote
remote: !include config/xiaomi_ir_remote.yaml

# Xiaomi Vacuum
vacuum:
  - platform: xiaomi_miio
    host: !secret host_vacuum
    token: !secret token_vacuum

# Google cast
media_player:
  - name: Chromcast
    platform: cast
    host: !secret host_chromecast
  - name: Nexus Player
    platform: cast
    host: !secret host_nexus_player

# Router
device_tracker:
  - name: Router
    platform: xiaomi
    host: !secret host_router
    password: !secret password_router
    consider_home: 30
    track_new_devices: no

# Telegram
notify:
  - name: Telegram
    platform: telegram
    chat_id: !secret chat_id_telegram

telegram_bot:
  platform: webhooks
  api_key: !secret api_key_telegram
  allowed_chat_ids:
    - !secret chat_id_telegram
