title: TechVille
resources:
  - url: /local/vertical-stack-in-card.js?v=0.4.1
    type: js
  - url: /local/button-card.js
    type: module
views:
  - path: home
    title: Home
    cards:
      - type: grid
        title: Indoor
        columns: 1
        square: false
        cards:
          - type: grid
            title: Temperature
            columns: 3
            square: false
            cards:
              - type: sensor
                name: Living room
                entity: sensor.bedroom_temperature
                graph: line
              - type: sensor
                name: Bedroom
                entity: sensor.bedroom_humidity_temp_sensor_temperature
                graph: line
              - type: sensor
                name: Small room
                entity: sensor.small_room_humidity_temp_sensor_temperature
                graph: line
          - type: grid
            title: Humidity
            columns: 3
            square: false
            cards:
              - type: sensor
                name: Living room
                icon: mdi:water-percent
                entity: sensor.bedroom_humidity
                graph: line
              - type: sensor
                name: Bedroom
                entity: sensor.bedroom_humidity_temp_sensor_humidity
                graph: line
              - type: sensor
                name: Small room
                entity: sensor.small_room_humidity_temp_sensor_humidity
                graph: line
          - type: grid
            title: Pressure
            columns: 2
            square: false
            cards:
              - type: sensor
                name: Bedroom
                entity: sensor.bedroom_humidity_temp_sensor_pressure
                graph: line
              - type: sensor
                name: Small room
                entity: sensor.small_room_humidity_temp_sensor_pressure
                graph: line
          - type: sensor
            name: Air Quality
            graph: line
            entity: sensor.bedroom_aqi
      - type: grid
        title: Outdoor
        columns: 1
        square: false
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.openweathermap_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.openweathermap_humidity
            graph: line
          - type: sensor
            name: Air Quality
            #entity: sensor.waqi_north_taipei_city_sinyi_taiwan
            entity: sensor.waqi_north_taipei_city_daan_taiwan
            graph: line

      - type: vertical-stack
        cards:
          - type: 'custom:vertical-stack-in-card'
            cards:
              - type: markdown
                content: '<ha-icon icon="mdi:account-multiple"></ha-icon> Home'
                style: |
                  ha-card { 
                    #background: rgba(0,0,0,0);
                    font-size: 20px;
                  }
              - type: horizontal-stack
                cards:
                  - type: 'custom:button-card'
                    entity: device_tracker.ludovic_mi9t
                    aspect_ratio: 4/4
                    show_name: false
                    show_icon: false
                    styles:
                      card:
                        - padding: 4%
                        - background-image: url("/local/images/ludo.png")
                        - background-size: 99%
                        - background-repeat: no-repeat
                        - background-position: top center
                      custom_fields:
                        location:
                          - text-transform: capitalize
                          - position: absolute
                          - left: 4%
                          - top: 4%
                          - color: >-
                              [[[ if (states["device_tracker.ludovic_mi9t"].state == "home")
                              return "#50F14F"; else return "#e45649"; ]]]
                        battery:
                          - align-self: right
                          - position: absolute
                          - right: 4%
                          - top: 4%
                          - color: >-
                              [[[ if (states["device_tracker.ludovic_mi9t"].attributes.battery_level <= 30)
                              return "#e45649"; if
                              (states["device_tracker.ludovic_mi9t"].attributes.battery_level <= 50) return
                              "#ffa229"; else return "#50F14F"; ]]]
                    custom_fields:
                      location: |
                        [[[
                          if (states["device_tracker.ludovic_mi9t"].state == "not_home")
                            return `<ha-icon
                              icon="mdi:home-export-outline"
                              style="width: 22px; height: 22px;">
                              </ha-icon>`
                          else if (states["device_tracker.ludovic_mi9t"].state == "office_ludovic")
                            return `<ha-icon
                              icon="mdi:office-building-outline"
                              style="width: 22px; height: 22px;">
                              </ha-icon>`
                          else
                            return `<ha-icon
                              icon="mdi:home"
                              style="width: 22px; height: 22px;">
                              </ha-icon>`
                        ]]]
                      battery: |
                        [[[
                          return `<ha-icon
                            icon="mdi:battery"
                            style="width: 20px; height: 20px;"></ha-icon
                            <span>${states['device_tracker.ludovic_mi9t'].attributes.battery_level}%</span>`
                        ]]]
                  - type: 'custom:button-card'
                    entity: device_tracker.tara_mia2
                    aspect_ratio: 4/4
                    show_name: false
                    show_icon: false
                    styles:
                      card:
                        - padding: 4%
                        - background-image: url("/local/images/tara.jpg")
                        - background-size: 99%
                        - background-repeat: no-repeat
                        - background-position: top center
                      custom_fields:
                        location:
                          - text-transform: capitalize
                          - position: absolute
                          - left: 4%
                          - top: 4%
                          - color: >-
                              [[[ if (states["device_tracker.tara_mia2"].state ==
                              "not_home") return "#e45649"; else return "#50F14F"; ]]]
                        battery:
                          - align-self: right
                          - position: absolute
                          - right: 4%
                          - top: 4%
                          - color: >-
                              [[[ if (states["device_tracker.tara_mia2"].attributes.battery_level <= 30)
                              return "#e45649"; if
                              (states["device_tracker.tara_mia2"].attributes.battery_level <= 50) return
                              "#ffa229"; else return "#50F14F"; ]]]
                    custom_fields:
                      location: |
                        [[[
                          if (states["device_tracker.tara_mia2"].state == "not_home")
                            return `<ha-icon
                              icon="mdi:home-export-outline"
                              style="width: 22px; height: 22px;">
                              </ha-icon>`
                          else 
                            return `<ha-icon
                              icon="mdi:home"
                              style="width: 22px; height: 22px;">
                              </ha-icon>`
                        ]]]
                      battery: |
                        [[[
                          return `<ha-icon
                            icon="mdi:battery"
                            style="width: 20px; height: 20px;"></ha-icon
                            <span>${states['device_tracker.tara_mia2'].attributes.battery_level}%</strong>`
                        ]]]
              - type: map
                entities:
                  - device_tracker.ludovic_mi9t
                  - device_tracker.tara_mia2
                hours_to_show: 1

      - type: vertical-stack
        cards:
          - type: iframe
            title: Weather radar
            aspect_ratio: 80%
            url: https://embed.windy.com/?24.727,121.393,8
          - type: weather-forecast
            entity: weather.openweathermap

  - path: control
    title: Control
    cards:
      - type: grid
        title: Lights
        columns: 3
        square: false
        cards:
          - type: light
            entity: light.living_room_table
          - type: light
            entity: light.tv_lights
          - type: light
            entity: light.living_room_main
          - type: light
            entity: light.bed
          - type: light
            entity: light.shower_room
          - type: light
            entity: light.small_room
      - type: grid
        title: Sensors
        columns: 1
        square: false
        cards:
          - type: glance
            title: Security
            entities:
              - binary_sensor.front_door_contact
              - binary_sensor.front_door_lock_contact
          - type: glance
            title: Occupancy
            entities:
              - binary_sensor.bedroom_motion_occupancy
              - binary_sensor.living_room_motion_occupancy
              - binary_sensor.shower_room_motion_occupancy
              - binary_sensor.kitchen_motion_occupancy
              - binary_sensor.broken_motion_occupancy
          - type: glance
            title: Others
            entities:
              - sensor.living_room_cube_action
              - sensor.small_room_switch_action
              - sensor.bedroom_switch_action
              - binary_sensor.shower_room_door_contact
              - vacuum.xiaomi_vacuum_cleaner

  - path: all_view
    title: All
    cards:
      - type: grid
        title: Power switch
        columns: 2
        cards:
          - type: sensor
            name: switch energy
            entity: sensor.thin_power_switch_energy
            graph: line
          - type: sensor
            name: switch power
            entity: sensor.thin_power_switch_power
            graph: line
          - type: sensor
            name: switch temperature
            entity: sensor.thin_power_switch_temperature
            graph: line
          - type: button
            name: switch
            entity: switch.thin_power_switch
      - type: entities
        entities:
          - device_tracker.ludovic_mi9t
          - device_tracker.tara_mia2
        title: People
        show_header_toggle: true
      - type: entities
        entities:
          - entity: group.security_sensor
            name: Sensor
          - group.alarm
        title: Security
        show_header_toggle: true
      - type: picture-entity
        entity: camera.living_room_live
      - type: media-control
        entity: media_player.tv_chomecast
      - type: media-control
        entity: media_player.teddy
      - type: media-control
        entity: media_player.bobby
      - type: entities
        entities:
          - light.bed_lights
          - light.shower_room
          - light.tv_lights
          - light.living_room_table
          - light.living_room_main
          - light.small_room
        title: Lights
        show_header_toggle: true
      - type: entities
        entities:
          - group.vacuum_schedule_weekdays
          - group.vacuum_schedule_weekend
          - vacuum.xiaomi_vacuum_cleaner
        title: Vacuum Remote
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.waqi_guting_taiwan_tai_wan_gu_ting
        title: Weather
        show_header_toggle: true
      - type: weather-forecast
        entity: weather.dark_sky
        show_forecast: false
      - type: entities
        entities:
          - sensor.bedroom_temperature
          - sensor.bedroom_humidity
          - sensor.bedroom_aqi
        title: Bedroom Sensors
        show_header_toggle: true
      - type: entities
        entities:
          - light.tv_lights
          - light.living_room_table
          - light.living_room_main
          - fan.mi_air_purifier_2
        title: Living Room
        show_header_toggle: true
      - type: entities
        entities:
          - binary_sensor.front_door_contact
          - binary_sensor.front_door_lock_contact
        title: Security Sensor
        show_header_toggle: true
      - type: entities
        entities:
          - light.bed
          - light.shower_room
        title: Lights Bedroom
        show_header_toggle: true
      - type: entities
        entities:
          - binary_sensor.bedroom_motion_occupancy
        title: Bed Sensors
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.vacuum_schedule_weekdays_template
          - input_boolean.vacuum_schedule_weekdays
          - input_number.vacuum_schedule_weekdays_hour
          - input_number.vacuum_schedule_weekdays_minute
          - input_datetime.only_time
        title: Georgie's Schedule (Weekdays)
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.vacuum_schedule_weekend_template
          - input_boolean.vacuum_schedule_weekend
          - input_number.vacuum_schedule_weekend_hour
          - input_number.vacuum_schedule_weekend_minute
        title: Georgie's Schedule (Weekend)
        show_header_toggle: true
      - type: entities
        entities:
          - binary_sensor.remote_ui
          - binary_sensor.updater
          - binary_sensor.workday_sensor
          - binary_sensor.living_room_motion_occupancy
          - binary_sensor.shower_room_door_contact
          - binary_sensor.shower_room_motion_occupancy
        title: Binary sensor
      - type: entities
        entities:
          - input_boolean.ac_interval_enabled
          - input_boolean.alarm_enabled_all
          - input_boolean.alarm_enabled
          - input_boolean.ac_delay_enabled
          - input_boolean.ac_time_slot_enabled
          - input_boolean.ac_timer_enabled
          - input_boolean.front_door_opened_long
        title: Input boolean
      - type: entities
        entities:
          - input_number.ac_interval_duration
          - input_number.ac_delay_hour
          - input_number.ac_timer_hour
          - input_number.ac_interval_min_temp
          - input_number.ac_delay_minute
          - input_number.ac_timer_minute
          - input_number.ac_interval_time
          - input_number.ac_start_hour
          - input_number.ac_start_minute
          - input_number.ac_stop_hour
          - input_number.ac_stop_minute
        title: Input number
      - type: entities
        entities:
          - light.bedroom_lights
          - light.dining_room_lights
          - light.living_room_lights
          - light.tv_back
          - light.tv_up
          - light.small_room
        title: Light
      - type: entities
        entities:
          - remote.bedroom_remote
        title: remote
      - type: entities
        entities:
          - sensor.living_room_cube_action
          - sensor.living_room_cube_linkquality
          - sensor.bedroom_motion_linkquality
          - sensor.front_door_linkquality
          - sensor.front_door_lock_linkquality
          - sensor.living_room_motion_linkquality
          - sensor.shower_room_door_linkquality
          - sensor.shower_room_motion_linkquality
          - sensor.bedroom_switch_action
          - sensor.bedroom_switch_linkquality
        title: Sensor
      - type: entities
        entities:
          - switch.smart_plug
        title: Switch

