input_number:
  ac_delay_hour:
    name: Hour
    icon: mdi:timer
    initial: 1
    min: 0
    max: 23
    step: 1
  ac_delay_minute:
    name: Minute
    icon: mdi:timer
    initial: 30
    min: 0
    max: 59
    step: 1

input_boolean:
  ac_delay_enabled:
    name: Enable delay
    initial: off
    icon: mdi:toggle-switch

timer:
  ac_delay:
    name: Delay
    icon: mdi:timer

sensor:
  platform: template
  sensors:
    delay_hour:
      value_template: '{{ states("input_number.ac_delay_hour") | round(0) }}'
    delay_minute:
      value_template: '{{ states("input_number.ac_delay_minute") | round(0) }}'
    delay_duration:
      value_template: >
        {% if states("input_boolean.ac_delay_enabled") %}
          {% if states("sensor.delay_hour") | length == 1 %}0{% endif %}{{states("sensor.delay_hour") }}:{% if states("sensor.delay_minute") | length == 1 %}0{% endif %}{{ states("sensor.delay_minute") }}:00
        {% else %}
          00:00:00
        {% endif %}

automation:
  - id: start_ac_delay
    trigger:
      platform: state
      entity_id: input_boolean.ac_delay_enabled
      from: 'off'
      to: 'on'
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ states("sensor.delay_hour") != 0 }}'
        - condition: template
          value_template: '{{ states("sensor.delay_minute") != 0 }}'
    action:
      - service: timer.start
        entity_id: timer.ac_delay
        data_template:
          duration: '{{ states("sensor.delay_duration") }}'

  - id: ac_delay_finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.ac_delay
    action:
      - service: script.turn_off_ludovics_ac

  - id: cancel_ac_delay
    trigger:
      platform: state
      entity_id: input_boolean.ac_delay_enabled
      from: 'on'
      to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.ac_delay

group:
  ac_set_delay:
    name: AC Set Delay
    entities:
      - input_number.ac_delay_hour
      - input_number.ac_delay_minute
      - timer.ac_delay
      - input_boolean.ac_delay_enabled
