input_number:
  ac_timer_hour:
    name: Hour
    icon: mdi:timer
    initial: 1
    min: 0
    max: 23
    step: 1
  ac_timer_minute:
    name: Minute
    icon: mdi:timer
    initial: 30
    min: 0
    max: 59
    step: 1

input_boolean:
  ac_timer_enabled:
    name: Enable timer
    initial: off
    icon: mdi:toggle-switch

timer:
  ac_timer:
    name: Timer
    icon: mdi:timer

sensor:
  platform: template
  sensors:
    timer_hour:
      value_template: '{{ states("input_number.ac_timer_hour") | round(0) }}'
    timer_minute:
      value_template: '{{ states("input_number.ac_timer_minute") | round(0) }}'
    timer_duration:
      value_template: >
        {% if states("input_boolean.ac_timer_enabled") %}
          {% if states("sensor.timer_hour") | length == 1 %}0{% endif %}{{states("sensor.timer_hour") }}:{% if states("sensor.timer_minute") | length == 1 %}0{% endif %}{{ states("sensor.timer_minute") }}:00
        {% else %}
          00:00:00
        {% endif %}

automation:
  - id: start_ac_timer
    trigger:
      platform: state
      entity_id: input_boolean.ac_timer_enabled
      from: 'off'
      to: 'on'
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ states("sensor.timer_hour") != 0 }}'
        - condition: template
          value_template: '{{ states("sensor.timer_minute") != 0 }}'
    action:
      - service: script.turn_on_ludovics_ac
      - service: timer.start
        entity_id: timer.ac_timer
        data_template:
          duration: '{{ states("sensor.timer_duration") }}'

  - id: stops_ac
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.ac_timer
    action:
      - service: script.turn_off_ludovics_ac

  - id: cancel_ac_timer
    trigger:
      platform: state
      entity_id: input_boolean.ac_timer_enabled
      from: 'on'
      to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.ac_timer

group:
  ac_set_timer:
    name: AC Set Timer
    entities:
      - input_number.ac_timer_hour
      - input_number.ac_timer_minute
      - timer.ac_timer
      - input_boolean.ac_timer_enabled
